---
abstract: 'PSGI application to serve remote (HTTP) subroutine call requests'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Spec-HTTP-Server
requires:
  Data::Format::Pretty: 0
  Data::Format::Pretty::HTML: 0
  Data::Format::Pretty::JSON: 0
  Data::Format::Pretty::PHPSerialization: 0
  Data::Format::Pretty::YAML: 0
  Data::Rmap: 0
  Gepok: 0
  Log::Any::Adapter: 0
  Log::Any::Adapter::Callback: 0.03
  Log::Any::App: 0
  Module::List: 0
  Plack: 0
  Starman: 0
  Sub::Spec: 1.0.1
  Sub::Spec::CmdLine: 0
  Sub::Spec::Gen::ForModule: 0
  Sub::Spec::GetArgs::Array: 0
  Sub::Spec::HTTP: 1.0.1
  Sub::Spec::To::Text::Usage: 0
  Sub::Spec::URI: 0.10
  Sub::Spec::URI::http: 0
  Test::More: 0.96
  URI::Escape: 0
  YAML::Syck: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Sub-Spec-HTTP-Server/
  repository: http://github.com/sharyanto/perl-Sub-Spec-HTTP-Server
version: 0.11
