---
abstract: 'Serve subroutine calls via HTTP/HTTPS'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Spec-HTTP-Server
requires:
  CGI::Lite: 0
  Capture::Tiny: 0
  HTTP::Daemon: 0
  HTTP::Daemon::SSL: 0
  HTTP::Parser: 0
  HTTP::Request::AsCGI: 0
  IO::Handle::Record: 0
  JSON: 0
  Log::Any: 0
  Log::Any::Adapter: 0
  Log::Any::Adapter::Callback: 0
  Moo: 0
  PHP::Serialization: 0
  Sub::Spec: 0.13
  Sub::Spec::Caller: 0
  Sub::Spec::CmdLine: 0
  Test::More: 0.96
  Time::HiRes: 0
  YAML::Syck: 0
  perl: 5.010000
resources:
  homepage: http://search.cpan.org/dist/Sub-Spec-HTTP-Server/
  repository: http://github.com/sharyanto/perl-Sub-Spec-HTTP-Server
version: 0.04
